# Copys the certs generated by caddy to the `caddy-certs/` directory
copy-certs:
	docker compose cp caddy:/usr/local/share/ca-certificates "./caddy-certs"

# Create the updates table in PostgreSQL
create-table:
	@echo "Creating updates table in PostgreSQL..."
	@docker compose exec -T db psql -U postgres -d sitdown -c "CREATE TABLE IF NOT EXISTS public.updates ( \
		update_id uuid DEFAULT uuidv7() NOT NULL, \
		username varchar NOT NULL, \
		description varchar NULL, \
		blocked bool DEFAULT false NOT NULL, \
		created_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL, \
		CONSTRAINT updates_pkey PRIMARY KEY (update_id) \
	);"
